### ISSUE TITLE
vaeac on small-ish datasets?

### ISSUE THREAD

**Issue by kieranrcampbell** [tigvarts/vaeac#1]
Hello,

Firstly, I really enjoyed the paper - congrats on the accept.

I've been trying to get vaeac to work on some non-imaging (real valued) data, but am struggling to get meaningful results on a small synthetic dataset:

If I generate some multivariate-gaussian distributed data (to ensure there is covariance between different features to enable imputation) like so:

```python
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(123)

N = 1000 # samples
G = 10 # features

W = np.random.normal(scale = .5, size=(G,G))
kappa = np.exp(np.random.normal(scale = .2, size = G))

K = W @ W.T + np.diag(kappa) # covariance matrix

X = np.random.multivariate_normal(mean = np.zeros(G), cov = K, size = N) # data

# (we can make sure the covariance structure is estimable from the data via np.cov(X.T))

# create a mask where variables are missing randomly 5%
mask = np.random.binomial(1, p = 0.05, size = (N,G))

# set to NA as required by vaeac
Y = X.copy()
Y[mask == 1] = np.nan

np.savetxt("../data/data.tsv", Y, delimiter="\t")
```
I can call vaeac using 50 epochs which seems ok for convergence:

```
python impute.py --input_file ../../data/data.tsv --output_file ../../data/vaeac-out.tsv --one_hot_max_size  1 1 1 1 1 1 1 1 1 1  --epochs 50 --validation_ratio 0.1
```

However, when I load the imputed data and plot one instance:

```python
Yo = np.loadtxt("../data/vaeac-out.tsv", delimiter="\t")
plt.scatter(X.reshape(-1), Yo[0:1000,:].reshape(-1))
```

![image](https://user-images.githubusercontent.com/2039489/58063357-ad71ac00-7b32-11e9-948c-87b7d4034325.png)

you see there is no correlation between the ground truth and values returned by vaeac. Any advice on getting this working for this sort of data size? Thanks!

**Comment by tigvarts** [comment]
Hello,

Thank you for your feedback and for the code reproducing the issue! I'll try to write it more clear in the documentation that by default the code produces multiple different imputations for one object and those imputations are consecutive in the output file. By default `num_imputations` is 5, so the output file is structured as follows
```
object1_imputation1
object1_imputation2
object1_imputation3
object1_imputation4
object1_imputation5
object2_imputation1
object2_imputation2
...
```

Therefore you have either to set `--num_imputations 1` when calling `impute.py` or to plot data using `Yo.reshape(N, -1, G).mean(1)` or `Yo.reshape(N, -1, G)[:, 0]`.

`Yo.reshape(N, -1, G).mean(1)` is recommended, because the averaged imputation outperforms a sample from the distribution over imputations in terms of the majority of the metrics.

Also it is better to plot imputed data only, i. e. to use `X[mask == 1].reshape(-1)` instead of `X.reshape(-1)`.

**Comment by kieranrcampbell** [comment]
Many thanks, I've implemented the changes as suggested and it works much better!
